export enum PrivilegeConst {
  ADMINISTRATION = "ADMINISTRATION",

  USER = "USER",
  USER_CREATE = "USER_CREATE",
  USER_EDIT = "USER_EDIT",
  USER_DELETE = "USER_DELETE",

  ROLE = "ROLE",
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_EDIT = "ROLE_EDIT",
  ROLE_DELETE = "ROLE_DELETE",

  PRIVILEGE = "PRIVILEGE",
  PRIVILEGE_CREATE = "PRIVILEGE_CREATE",
  PRIVILEGE_EDIT = "PRIVILEGE_EDIT",
  PRIVILEGE_DELETE = "PRIVILEGE_DELETE",

  AUDITLOG = "AUDITLOG",
  AUDITLOG_CREATE = "AUDITLOG_CREATE",
  AUDITLOG_EDIT = "AUDITLOG_EDIT",
  AUDITLOG_DELETE = "AUDITLOG_DELETE",


  CATEGORY = "CATEGORY",

  COUNTRY = "COUNTRY",
  COUNTRY_CREATE = "COUNTRY_CREATE",
  COUNTRY_EDIT = "COUNTRY_EDIT",
  COUNTRY_DELETE = "COUNTRY_DELETE",

  PROVINCE = "PROVINCE",
  PROVINCE_CREATE = "PROVINCE_CREATE",
  PROVINCE_EDIT = "PROVINCE_EDIT",
  PROVINCE_DELETE = "PROVINCE_DELETE",

  DISTRICT = "DISTRICT",
  DISTRICT_CREATE = "DISTRICT_CREATE",
  DISTRICT_EDIT = "DISTRICT_EDIT",
  DISTRICT_DELETE = "DISTRICT_DELETE",

  GROUPITEM = "GROUPITEM",
  GROUPITEM_CREATE = "GROUPITEM_CREATE",
  GROUPITEM_EDIT = "GROUPITEM_EDIT",
  GROUPITEM_DELETE = "GROUPITEM_DELETE",

  ITEM = "ITEM",
  ITEM_CREATE = "ITEM_CREATE",
  ITEM_EDIT = "ITEM_EDIT",
  ITEM_DELETE = "ITEM_DELETE",

  SUPPLY = "SUPPLY",
  SUPPLY_CREATE = "SUPPLY_CREATE",
  SUPPLY_EDIT = "SUPPLY_EDIT",
  SUPPLY_DELETE = "SUPPLY_DELETE",

  NOTIFY = "NOTIFY",
  NOTIFY_CREATE = "NOTIFY_CREATE",
  NOTIFY_EDIT = "NOTIFY_EDIT",
  NOTIFY_DELETE = "NOTIFY_DELETE",

  UNIT = "UNIT",
  UNIT_CREATE = "UNIT_CREATE",
  UNIT_EDIT = "UNIT_EDIT",
  UNIT_DELETE = "UNIT_DELETE",

  SHOP = "SHOP",
  SHOP_CREATE = "SHOP_CREATE",
  SHOP_EDIT = "SHOP_EDIT",
  SHOP_DELETE = "SHOP_DELETE",

  SUPPLIER = "SUPPLIER",
  SUPPLIER_CREATE = "SUPPLIER_CREATE",
  SUPPLIER_EDIT = "SUPPLIER_EDIT",
  SUPPLIER_DELETE = "SUPPLIER_DELETE",

  CONTACT = "CONTACT",
  CONTACT_CREATE = "CONTACT_CREATE",
  CONTACT_EDIT = "CONTACT_EDIT",
  CONTACT_DELETE = "CONTACT_DELETE",

  SHOPORDER = "SHOPORDER",
  SHOPORDER_CREATE = "SHOPORDER_CREATE",
  SHOPORDER_EDIT = "SHOPORDER_EDIT",
  SHOPORDER_DELETE = "SHOPORDER_DELETE",
  SHOPORDERDETAIL = "SHOPORDERDETAIL",
  SHOPORDERDETAIL_CREATE = "SHOPORDERDETAIL_CREATE",
  SHOPORDERDETAIL_EDIT = "SHOPORDERDETAIL_EDIT",
  SHOPORDERDETAIL_DELETE = "SHOPORDERDETAIL_DELETE",

  SHOPIMPORT = "SHOPIMPORT",
  SHOPIMPORT_CREATE = "SHOPIMPORT_CREATE",
  SHOPIMPORT_EDIT = "SHOPIMPORT_EDIT",
  SHOPIMPORT_DELETE = "SHOPIMPORT_DELETE",
  SHOPIMPORTDETAIL = "SHOPIMPORTDETAIL",
  SHOPIMPORTDETAIL_CREATE = "SHOPIMPORTDETAIL_CREATE",
  SHOPIMPORTDETAIL_EDIT = "SHOPIMPORTDETAIL_EDIT",
  SHOPIMPORTDETAIL_DELETE = "SHOPIMPORTDETAIL_DELETE",

  SHOPEXPORT = "SHOPEXPORT",
  SHOPEXPORT_CREATE = "SHOPEXPORT_CREATE",
  SHOPEXPORT_EDIT = "SHOPEXPORT_EDIT",
  SHOPEXPORT_DELETE = "SHOPEXPORT_DELETE",
  SHOPEXPORTDETAIL = "SHOPEXPORTDETAIL",
  SHOPEXPORTDETAIL_CREATE = "SHOPEXPORTDETAIL_CREATE",
  SHOPEXPORTDETAIL_EDIT = "SHOPEXPORTDETAIL_EDIT",
  SHOPEXPORTDETAIL_DELETE = "SHOPEXPORTDETAIL_DELETE",
}
