eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8764
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.148.50.4:1521/DEVPDB.prudential.com
    username: utility
    password: 123qwe
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
logging:
  file:
    name: ./logs/auth-server.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/auth-server.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      total-size-cap: 1000MB
      max-history: 90
      clean-history-on-start: false
