server:
  port: 8101
spring:
  application:
    name: gallery-service
  config:
    import: application.properties
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
  dashboard:
    proxy-stream-allow-list: localhost
