eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8101
spring:
  application:
    name: gallery-service
  config:
    import: application.properties
logging:
  file: ${logging.path}/${spring.application.name}.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.path}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      total-size-cap: 1000MB
      max-history: 90
      clean-history-on-start: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
