eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8101
spring:
  application:
    name: gallery-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
