eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: zuul-server
  config:
    import: application.properties
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.148.108.12:1521/DEVPDB.prudential.com
    username: utility
    password: 123qwe
  jpa:
    show-sql: true
    open-in-view: false
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
zuul:
  SendErrorFilter:
    post:
      disable: true
  # A prefix that can added to beginning of all requests.
#  prefix: /api
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignored-services: '*'
  routes:
    # Map path to auth service
#    auth-server:
#      path: /auth/**
#      # Exclude authorization from sensitive headers
#      sensitive-headers: Cookie,Set-Cookie
#      service-id: auth-server
#      # By default, all requests to gallery service for example will start with: "/gallery/"
#      # What will be sent to the gallery service is what comes after the path defined,
#      # So, if request is "/gallery/view/1", gallery service will get "/view/1". /auth = /auth/auth
#      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
#      strip-prefix: false
#    # Map paths to gallery-service
    gallery-service:
      path: /gallery/**
      service-id: gallery-service
    auth-service:
      path: /auth/**
      service-id: auth-service
    order-service:
      path: /order/**
      service-id: order-service
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      auth-service:
        - limit: 5 #optional - request number limit per refresh interval window
          refresh-interval: 60 #default value (in seconds)
          type:
            - origin
      order-service:
        - limit: 100 #optional - request number limit per refresh interval window
          refresh-interval: 60 #default value (in seconds)
          type:
            - origin
# timeout
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
