server:
  port: 8763
spring:
  application:
    name: board-service
  config:
    import: application.properties
  boot:
    admin:
      context-path: /admin
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${server.kafka.host}:${server.kafka.port}
      bindings:
        turbineStreamInput:
          destination: turbineStreamTopic
          group: turbine-stream-group
#          content-type: application/json
#  rabbitmq:
#    host: 10.148.50.84
#    port: 5672
#    username: admin
#    password: admin
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
