spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${auth-service.db.url}
    username: ${auth-service.db.username}
    password: ${auth-service.db.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
    producer:
      bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: ${server.kafka.topic.log}
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
