spring:
  boot:
    admin:
      context-path: /admin
  security:
    user:
      name: ${account.board-service.username}
      password: ${account.board-service.password}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${server.kafka.host}:${server.kafka.port}
      bindings:
        turbineStreamInput:
          destination: turbineStreamTopic
          group: turbine-stream-group
#          content-type: application/json
#  rabbitmq:
#    host: 10.148.50.84
#    port: 5672
#    username: admin
#    password: admin
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
