spring:
  kafka:
    bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
    topic:
      name: order_topics
    consumer:
      bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
