eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  security:
    user:
      name: ${account.eureka-service.username}
      password: ${account.eureka-service.password}
