eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  security:
    user:
      name: ${account.eureka-service.username}
      password: ${account.eureka-service.password}
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
