spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${server.kafka.host}:${server.kafka.port}
      bindings:
        hystrixStreamOutput:
          destination: turbineStreamTopic
          group: turbine-stream-group
          producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
