spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${auth-service.db.url}
    username: ${auth-service.db.username}
    password: ${auth-service.db.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
    topic:
      name: ${server.kafka.topic.log}
    consumer:
      bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
      group-id: log_consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
