spring:
  kafka:
    bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
    producer:
      bootstrap-servers: ${server.kafka.host}:${server.kafka.port}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: order_topics
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${server.kafka.host}:${server.kafka.port}
      bindings:
        hystrixStreamOutput:
          destination: turbineStreamTopic
          group: turbine-stream-group
          producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
