server:
  port: 8762
spring:
  application:
    name: zuul-service
  config:
    import: application.properties
  security:
    user:
      name: zuul          # not use
      password: zuul#123  # not use
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.gz
zuul:
  SendErrorFilter:
    post:
      disable: true
  # A prefix that can added to beginning of all requests.
#  prefix: /api
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignored-services: '*'
  routes:
    # Map path to auth service
#    auth-server:
#      path: /auth/**
#      # Exclude authorization from sensitive headers
#      sensitive-headers: Cookie,Set-Cookie
#      service-id: auth-server
#      # By default, all requests to gallery service for example will start with: "/gallery/"
#      # What will be sent to the gallery service is what comes after the path defined,
#      # So, if request is "/gallery/view/1", gallery service will get "/view/1". /auth = /auth/auth
#      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
#      strip-prefix: false
#    # Map paths to gallery-service
    gallery-service:
      path: /gallery/**
      service-id: gallery-service
    image-service:
      path: /image/**
      service-id: image-service
    auth-service:
      path: /auth/**
      service-id: auth-service
    order-service:
      path: /order/**
      service-id: order-service
    portalapi-service:
      path: /portalapi/**
      service-id: portalapi-service
  ratelimit:
    enabled: true
    repository: REDIS # JPA
    policy-list:
      auth-service:
        - limit: 3 #optional - request number limit per refresh interval window
          refresh-interval: 60 #default value (in seconds)
          type:
            - origin
      order-service:
        - limit: 100 #optional - request number limit per refresh interval window
          refresh-interval: 60 #default value (in seconds)
          type:
            - origin
# timeout
#  host:
#    connect-timeout-millis: 5000
#    socket-timeout-millis: 10000
#    max-per-route-connections: 50
#    max-total-connections: 200
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 10000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
#  OkToRetryOnAllOperations: true
redis:
  host: ${server.redis.host}
  port: ${server.redis.port}
springdoc:
  swagger-ui:
    urls:
      - name: zuul-service
        url: /v3/api-docs
      - name: gallery-service
        url: /gallery/v3/api-docs
      - name: image-service
        url: /image/v3/api-docs
      - name: order-service
        url: /order/v3/api-docs
      - name: portalapi-service
        url: /portalapi/v3/api-docs
